-- MySQL Script generated by MySQL Workbench
-- Wed Feb 24 10:26:11 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`KLUB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`KLUB` (
  `NAZWA` VARCHAR(45) NOT NULL,
  `Numer telefonu` INT NOT NULL,
  `Godziny otwarcia` VARCHAR(20) NULL,
  `Kod` VARCHAR(10) NOT NULL,
  `Miasto` VARCHAR(45) NOT NULL,
  `Ulica` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NAZWA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TRENER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TRENER` (
  `Mail` VARCHAR(45) NOT NULL,
  `Abonament` VARCHAR(1) NOT NULL,
  `Numer Konta bankowego` VARCHAR(45) NOT NULL,
  `Imie` VARCHAR(45) NOT NULL,
  `Nazwisko` VARCHAR(45) NOT NULL,
  `Numer Telefonu` INT NOT NULL,
  PRIMARY KEY (`Mail`),
  UNIQUE INDEX `Numer Telefonu_UNIQUE` (`Numer Telefonu` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PLAN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PLAN` (
  `Nazwa` VARCHAR(45) NOT NULL,
  `Typ` VARCHAR(45) NOT NULL,
  `Poziom Zaawansowania` VARCHAR(45) NOT NULL,
  `TRENER_Mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TRENER_Mail`, `Nazwa`),
  CONSTRAINT `fk_PLAN_TRENER1`
    FOREIGN KEY (`TRENER_Mail`)
    REFERENCES `mydb`.`TRENER` (`Mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TRENING_W_PLANIE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TRENING_W_PLANIE` (
  `ID_treningu` VARCHAR(45) NOT NULL,
  `Rodzaj` VARCHAR(45) NOT NULL,
  `Poziom zaawansowania` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_treningu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ĆWICZENIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ĆWICZENIA` (
  `Grupa mięśniowa` VARCHAR(45) NOT NULL,
  `Poziom zaawansowania` VARCHAR(45) NOT NULL,
  `nazwa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nazwa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`KLIENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`KLIENT` (
  `Mail` VARCHAR(45) NOT NULL,
  `Imię` VARCHAR(45) NOT NULL,
  `Nazwisko` VARCHAR(45) NOT NULL,
  `Numer telefonu` VARCHAR(45) NOT NULL,
  `pakiet` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`Mail`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trening grupowy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trening grupowy` (
  `maksymalna liczba uczestnikow` INT NOT NULL,
  `ID_treningu_grupowego` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_treningu_grupowego`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trening idywidualny`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trening idywidualny` (
  `akceptacja treningu` INT NOT NULL,
  `ID_treningu_indywidualnego` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_treningu_indywidualnego`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TRENING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TRENING` (
  `Nazwa` VARCHAR(45) NOT NULL,
  `Poziom zaawansowania` VARCHAR(45) NOT NULL,
  `Typ` VARCHAR(45) NOT NULL,
  `Czas trwania` VARCHAR(45) NOT NULL,
  `trening grupowy_ID_treningu_grupowego` VARCHAR(45) NOT NULL,
  `trening idywidualny_ID_treningu_indywidualnego` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nazwa`, `trening grupowy_ID_treningu_grupowego`, `trening idywidualny_ID_treningu_indywidualnego`),
  INDEX `fk_TRENING_trening grupowy1_idx` (`trening grupowy_ID_treningu_grupowego` ASC) VISIBLE,
  INDEX `fk_TRENING_trening idywidualny1_idx` (`trening idywidualny_ID_treningu_indywidualnego` ASC) VISIBLE,
  CONSTRAINT `fk_TRENING_trening grupowy1`
    FOREIGN KEY (`trening grupowy_ID_treningu_grupowego`)
    REFERENCES `mydb`.`trening grupowy` (`ID_treningu_grupowego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRENING_trening idywidualny1`
    FOREIGN KEY (`trening idywidualny_ID_treningu_indywidualnego`)
    REFERENCES `mydb`.`trening idywidualny` (`ID_treningu_indywidualnego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`WYDARZENIE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`WYDARZENIE` (
  `Data` VARCHAR(45) NOT NULL,
  `godzina` VARCHAR(45) NOT NULL,
  `KLUB_NAZWA` VARCHAR(45) NOT NULL,
  `TRENING_Nazwa` VARCHAR(45) NOT NULL,
  `TRENER_Mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Data`, `KLUB_NAZWA`, `TRENING_Nazwa`, `TRENER_Mail`),
  INDEX `fk_WYDARZENIE_KLUB1_idx` (`KLUB_NAZWA` ASC) VISIBLE,
  INDEX `fk_WYDARZENIE_TRENING1_idx` (`TRENING_Nazwa` ASC) VISIBLE,
  INDEX `fk_WYDARZENIE_TRENER1_idx` (`TRENER_Mail` ASC) VISIBLE,
  CONSTRAINT `fk_WYDARZENIE_KLUB1`
    FOREIGN KEY (`KLUB_NAZWA`)
    REFERENCES `mydb`.`KLUB` (`NAZWA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WYDARZENIE_TRENING1`
    FOREIGN KEY (`TRENING_Nazwa`)
    REFERENCES `mydb`.`TRENING` (`Nazwa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WYDARZENIE_TRENER1`
    FOREIGN KEY (`TRENER_Mail`)
    REFERENCES `mydb`.`TRENER` (`Mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Przypisany domyślnie do`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Przypisany domyślnie do` (
  `KLUB_NAZWA` VARCHAR(45) NOT NULL,
  `TRENER_Mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`KLUB_NAZWA`, `TRENER_Mail`),
  INDEX `fk_KLUB_has_TRENER_TRENER1_idx` (`TRENER_Mail` ASC) VISIBLE,
  INDEX `fk_KLUB_has_TRENER_KLUB_idx` (`KLUB_NAZWA` ASC) VISIBLE,
  CONSTRAINT `fk_KLUB_has_TRENER_KLUB`
    FOREIGN KEY (`KLUB_NAZWA`)
    REFERENCES `mydb`.`KLUB` (`NAZWA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_KLUB_has_TRENER_TRENER1`
    FOREIGN KEY (`TRENER_Mail`)
    REFERENCES `mydb`.`TRENER` (`Mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Klienci_w_klubie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Klienci_w_klubie` (
  `KLUB_NAZWA` VARCHAR(45) NOT NULL,
  `KLIENT_Mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`KLUB_NAZWA`, `KLIENT_Mail`),
  INDEX `fk_KLUB_has_KLIENT_KLIENT1_idx` (`KLIENT_Mail` ASC) VISIBLE,
  INDEX `fk_KLUB_has_KLIENT_KLUB1_idx` (`KLUB_NAZWA` ASC) VISIBLE,
  CONSTRAINT `fk_KLUB_has_KLIENT_KLUB1`
    FOREIGN KEY (`KLUB_NAZWA`)
    REFERENCES `mydb`.`KLUB` (`NAZWA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_KLUB_has_KLIENT_KLIENT1`
    FOREIGN KEY (`KLIENT_Mail`)
    REFERENCES `mydb`.`KLIENT` (`Mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zapisal_sie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zapisal_sie` (
  `KLIENT_Mail` VARCHAR(45) NOT NULL,
  `WYDARZENIE_Data` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`KLIENT_Mail`, `WYDARZENIE_Data`),
  INDEX `fk_KLIENT_has_WYDARZENIE_WYDARZENIE1_idx` (`WYDARZENIE_Data` ASC) VISIBLE,
  INDEX `fk_KLIENT_has_WYDARZENIE_KLIENT1_idx` (`KLIENT_Mail` ASC) VISIBLE,
  CONSTRAINT `fk_KLIENT_has_WYDARZENIE_KLIENT1`
    FOREIGN KEY (`KLIENT_Mail`)
    REFERENCES `mydb`.`KLIENT` (`Mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_KLIENT_has_WYDARZENIE_WYDARZENIE1`
    FOREIGN KEY (`WYDARZENIE_Data`)
    REFERENCES `mydb`.`WYDARZENIE` (`Data`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Czy_klient_byl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Czy_klient_byl` (
  `KLIENT_Mail` VARCHAR(45) NOT NULL,
  `WYDARZENIE_Data` VARCHAR(45) NOT NULL,
  `Obecnosc` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`KLIENT_Mail`, `WYDARZENIE_Data`),
  INDEX `fk_KLIENT_has_WYDARZENIE_WYDARZENIE2_idx` (`WYDARZENIE_Data` ASC) VISIBLE,
  INDEX `fk_KLIENT_has_WYDARZENIE_KLIENT2_idx` (`KLIENT_Mail` ASC) VISIBLE,
  CONSTRAINT `fk_KLIENT_has_WYDARZENIE_KLIENT2`
    FOREIGN KEY (`KLIENT_Mail`)
    REFERENCES `mydb`.`KLIENT` (`Mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_KLIENT_has_WYDARZENIE_WYDARZENIE2`
    FOREIGN KEY (`WYDARZENIE_Data`)
    REFERENCES `mydb`.`WYDARZENIE` (`Data`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Trening_ćwiczenia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Trening_ćwiczenia` (
  `TRENING_W_PLANIE_ID_treningu` VARCHAR(45) NOT NULL,
  `ĆWICZENIA_nazwa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TRENING_W_PLANIE_ID_treningu`, `ĆWICZENIA_nazwa`),
  INDEX `fk_TRENING_W_PLANIE_has_ĆWICZENIA_ĆWICZENIA1_idx` (`ĆWICZENIA_nazwa` ASC) VISIBLE,
  INDEX `fk_TRENING_W_PLANIE_has_ĆWICZENIA_TRENING_W_PLANIE1_idx` (`TRENING_W_PLANIE_ID_treningu` ASC) VISIBLE,
  CONSTRAINT `fk_TRENING_W_PLANIE_has_ĆWICZENIA_TRENING_W_PLANIE1`
    FOREIGN KEY (`TRENING_W_PLANIE_ID_treningu`)
    REFERENCES `mydb`.`TRENING_W_PLANIE` (`ID_treningu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRENING_W_PLANIE_has_ĆWICZENIA_ĆWICZENIA1`
    FOREIGN KEY (`ĆWICZENIA_nazwa`)
    REFERENCES `mydb`.`ĆWICZENIA` (`nazwa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Plan_trening`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Plan_trening` (
  `PLAN_Nazwa` VARCHAR(45) NOT NULL,
  `TRENING_W_PLANIE_ID_treningu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PLAN_Nazwa`, `TRENING_W_PLANIE_ID_treningu`),
  INDEX `fk_PLAN_has_TRENING_W_PLANIE_TRENING_W_PLANIE1_idx` (`TRENING_W_PLANIE_ID_treningu` ASC) VISIBLE,
  INDEX `fk_PLAN_has_TRENING_W_PLANIE_PLAN1_idx` (`PLAN_Nazwa` ASC) VISIBLE,
  CONSTRAINT `fk_PLAN_has_TRENING_W_PLANIE_PLAN1`
    FOREIGN KEY (`PLAN_Nazwa`)
    REFERENCES `mydb`.`PLAN` (`Nazwa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PLAN_has_TRENING_W_PLANIE_TRENING_W_PLANIE1`
    FOREIGN KEY (`TRENING_W_PLANIE_ID_treningu`)
    REFERENCES `mydb`.`TRENING_W_PLANIE` (`ID_treningu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
